import $ from 'jquery'

const algeria_states = [
    { wilaya_code: '01', wilaya_name: 'أدرار' },
    { wilaya_code: '02', wilaya_name: ' الشلف' },
    { wilaya_code: '03', wilaya_name: 'الأغواط' },
    { wilaya_code: '04', wilaya_name: 'أم البواقي' },
    { wilaya_code: '05', wilaya_name: 'باتنة' },
    { wilaya_code: '06', wilaya_name: ' بجاية' },
    { wilaya_code: '07', wilaya_name: 'بسكرة' },
    { wilaya_code: '08', wilaya_name: 'بشار' },
    { wilaya_code: '09', wilaya_name: 'البليدة' },
    { wilaya_code: '10', wilaya_name: 'البويرة' },
    { wilaya_code: '11', wilaya_name: 'تمنراست' },
    { wilaya_code: '12', wilaya_name: 'تبسة' },
    { wilaya_code: '13', wilaya_name: 'تلمسان' },
    { wilaya_code: '14', wilaya_name: 'تيارت' },
    { wilaya_code: '15', wilaya_name: 'تيزي وزو' },
    { wilaya_code: '16', wilaya_name: 'الجزائر' },
    { wilaya_code: '17', wilaya_name: 'الجلفة' },
    { wilaya_code: '18', wilaya_name: 'جيجل' },
    { wilaya_code: '19', wilaya_name: 'سطيف' },
    { wilaya_code: '20', wilaya_name: 'سعيدة' },
    { wilaya_code: '21', wilaya_name: 'سكيكدة' },
    { wilaya_code: '22', wilaya_name: 'سيدي بلعباس' },
    { wilaya_code: '23', wilaya_name: 'عنابة' },
    { wilaya_code: '24', wilaya_name: 'قالمة' },
    { wilaya_code: '25', wilaya_name: 'قسنطينة' },
    { wilaya_code: '26', wilaya_name: 'المدية' },
    { wilaya_code: '27', wilaya_name: 'مستغانم' },
    { wilaya_code: '28', wilaya_name: 'المسيلة' },
    { wilaya_code: '29', wilaya_name: 'معسكر' },
    { wilaya_code: '30', wilaya_name: 'ورقلة' },
    { wilaya_code: '31', wilaya_name: 'وهران' },
    { wilaya_code: '32', wilaya_name: 'البيض' },
    { wilaya_code: '33', wilaya_name: 'إليزي' },
    { wilaya_code: '34', wilaya_name: 'برج بوعريريج' },
    { wilaya_code: '35', wilaya_name: 'بومرداس' },
    { wilaya_code: '36', wilaya_name: 'الطارف' },
    { wilaya_code: '37', wilaya_name: 'تندوف' },
    { wilaya_code: '38', wilaya_name: 'تيسمسيلت' },
    { wilaya_code: '39', wilaya_name: 'الوادي' },
    { wilaya_code: '40', wilaya_name: 'خنشلة' },
    { wilaya_code: '41', wilaya_name: 'سوق أهراس' },
    { wilaya_code: '42', wilaya_name: 'تيبازة' },
    { wilaya_code: '43', wilaya_name: 'ميلة' },
    { wilaya_code: '44', wilaya_name: 'عين الدفلة' },
    { wilaya_code: '45', wilaya_name: 'النعامة' },
    { wilaya_code: '46', wilaya_name: 'عين تيموشنت' },
    { wilaya_code: '47', wilaya_name: 'غرداية' },
    { wilaya_code: '48', wilaya_name: 'غليزان' },
    { wilaya_code: '49', wilaya_name: 'تيميمون' },
    { wilaya_code: '50', wilaya_name: 'برج باجي مختار' },
    { wilaya_code: '51', wilaya_name: 'أولاد جلال' },
    { wilaya_code: '52', wilaya_name: 'بني عباس' },
    { wilaya_code: '53', wilaya_name: 'عين صالح' },
    { wilaya_code: '54', wilaya_name: 'عين قزام' },
    { wilaya_code: '55', wilaya_name: 'تقرت' },
    { wilaya_code: '56', wilaya_name: 'جانت' },
    { wilaya_code: '57', wilaya_name: 'المغير' },
    { wilaya_code: '58', wilaya_name: 'المنيعة' }
]

$('.algeria_states').append(
    algeria_states.map(state=>`<option value="${state.wilaya_code}">${state.wilaya_name}</option>`)
)

